CREATE TABLE IF NOT EXISTS stats (
    player MEDIUMINT,
    game VARCHAR(8),
    team VARCHAR(3),
    pass_completions SMALLINT,
    pass_attempts SMALLINT,
    pass_yards SMALLINT,
    pass_cay SMALLINT,
    pass_yac SMALLINT,
    pass_drops SMALLINT,
    pass_bad_throws SMALLINT,
    pass_pressured SMALLINT,
    pass_blitzed SMALLINT,
    pass_scrambles SMALLINT,
    rush_attempts SMALLINT,
    rush_yards SMALLINT,
    rush_touchdowns SMALLINT,
    rush_ybc SMALLINT,
    rush_yac SMALLINT,
    rush_broken_tackles SMALLINT,
    recv_targets SMALLINT,
    recv_receptions SMALLINT,
    recv_yards SMALLINT,
    recv_touchdowns SMALLINT,
    recv_yac SMALLINT,
    recv_ybc SMALLINT,
    recv_broken_tackles SMALLINT,
    recv_drops SMALLINT,
    snaps SMALLINT,
    snap_pct SMALLINT,
    FOREIGN KEY (player) REFERENCES player(id),
    FOREIGN KEY (game) REFERENCES game(id),
    FOREIGN KEY (team) REFERENCES team(id)
);